name: Validate & Publish

on:
  push:
    branches-ignore:
      - gh-pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build
        run: bundle exec jekyll build
      
      - name: Validate HTML output
        run: bundle exec htmlproofer ./_site --ignore-missing-alt --disable-external
