name: Validate & Publish

on:
  push:
    branches-ignore:
      - gh-pages

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: true

      - name: Build
        run: bundle exec jekyll build

      - name: Validate HTML output
        run: bundle exec htmlproofer ./_site --ignore-missing-alt --disable-external
